// Build-time image pipeline for the static images in `public/images`.
//
// Why this exists: the hero photographs and editorial plates are supplied at
// camera resolution (1–7 MB each, ~78 MB in total). Everything in `public/` is
// copied into the build output verbatim and Cloudflare Pages serves those bytes
// exactly as they are, so without this step every visitor — including phone
// visitors — downloads full-resolution originals.
//
// For every raster image under `public/images` the script:
//
//   1. writes a ladder of resized WebP derivatives to `public/images/opt/`
//      (480 / 768 / 1024 / 1440 / 1920 px wide, quality 74 — visually
//      indistinguishable from the source at the sizes the site displays them),
//      skipping widths larger than the source;
//   2. names each derivative `<name>.<hash>-<width>.webp`, where `<hash>` comes
//      from the source bytes. Fingerprinted names are what let `public/_headers`
//      cache them as `immutable` for a year;
//   3. records the geometry in `src/data/image-manifest.ts`, which
//      `src/lib/images.ts` and `src/components/ResponsiveImage.astro` read to
//      build `srcset`/`sizes` and reserve layout space (`width`/`height`, so no
//      layout shift while the picture loads).
//
// The originals stay in `public/images` and remain the `<img src>` fallback for
// the small number of browsers without WebP support, and the social preview
// image (crawlers are inconsistent about WebP).
//
// The work is incremental: a derivative is rewritten only when the source file
// is newer, the derivative is missing, or PIPELINE_VERSION changed — so repeat
// builds and local `npm run dev` starts are cheap. `npm run images` runs it on
// demand; `prebuild` and `predev` keep it in step automatically.

import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const SOURCE_DIR = path.join(ROOT, "public", "images");
const OUTPUT_DIR = path.join(SOURCE_DIR, "opt");
const MANIFEST_FILE = path.join(ROOT, "src", "data", "image-manifest.ts");

// Bump this when the ladder, quality or output format changes, so existing
// derivatives are treated as stale and regenerated.
const PIPELINE_VERSION = 1;

const WIDTHS = [480, 768, 1024, 1440, 1920];
const MAX_WIDTH = WIDTHS[WIDTHS.length - 1];
const QUALITY = 74;
const EFFORT = 4; // sharp's WebP encoder effort (0–6); 4 is a good speed/size mix
const EXTENSIONS = new Set([".jpg", ".jpeg", ".png"]);
// `opt/` is this script's own output; `placeholders/` holds the hand-drawn SVG
// figures, which are already tiny and cannot be rasterised usefully.
const SKIP_DIRECTORIES = new Set(["opt", "placeholders"]);

const kb = (bytes) => `${(bytes / 1024).toFixed(0)} kB`;


/** Recursively list raster source images, skipping the directories above. */
async function collectSources(directory, found = []) {
	const entries = await readdir(directory, { withFileTypes: true });
	for (const entry of entries) {
		const full = path.join(directory, entry.name);
		if (entry.isDirectory()) {
			if (SKIP_DIRECTORIES.has(entry.name)) continue;
			await collectSources(full, found);
		} else if (EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
			found.push(full);
		}
	}
	return found;
}

/** The public URL a file under `public/` is served from (always forward slashes). */
const publicPath = (absolutePath) =>
	`/${path.relative(path.join(ROOT, "public"), absolutePath).split(path.sep).join("/")}`;

async function buildVariant(contents, hash, name, targetWidth, sourceMtime, sourceWidth, sourceHeight) {
	const file = `${name}.${hash}-${targetWidth}.webp`;
	const output = path.join(OUTPUT_DIR, file);
	const targetHeight = Math.max(1, Math.round((targetWidth / sourceWidth) * sourceHeight));

	// Skipped when an up-to-date derivative already exists on disk.
	let skipped = false;
	try {
		skipped = (await stat(output)).mtimeMs >= sourceMtime;
	} catch {
		skipped = false;
	}

	if (!skipped) {
		await sharp(contents)
			.resize({ width: targetWidth, withoutEnlargement: true, fit: "inside" })
			.webp({ quality: QUALITY, effort: EFFORT })
			.toFile(output);
	}

	return { variant: { w: targetWidth, h: targetHeight, file }, skipped };
}

/** Write the manifest only when its contents change, so it does not churn. */
async function writeManifest(images) {
	const body = `// AUTO-GENERATED by scripts/optimise-images.mjs — do not edit by hand.
// Regenerate with \`npm run images\` (also run automatically by prebuild/predev).
//
// Maps each source image's public URL to its intrinsic size and the resized
// WebP derivatives available for it. Consumed by src/lib/images.ts.

export interface ImageVariant {
\t/** Width in pixels. */
\tw: number;
\t/** Height in pixels — used for the width/height attributes that reserve space. */
\th: number;
\t/** File name within /images/opt/. */
\tfile: string;
}

export interface ImageRecord {
\t/** Intrinsic width of the original image. */
\twidth: number;
\t/** Intrinsic height of the original image. */
\theight: number;
\t/** Source-content hash embedded in every derivative file name. */
\thash: string;
\t/** Derivatives, narrowest first. */
\tvariants: ImageVariant[];
}

export const PIPELINE_VERSION = ${PIPELINE_VERSION};

export const IMAGE_MANIFEST: Record<string, ImageRecord> = ${JSON.stringify(images, null, "\t")};
`;

	let existing = null;
	try {
		existing = await readFile(MANIFEST_FILE, "utf8");
	} catch {
		// First run — no manifest yet.
	}
	if (existing === body) return;

	await mkdir(path.dirname(MANIFEST_FILE), { recursive: true });
	await writeFile(MANIFEST_FILE, body, "utf8");
}

async function main() {
	const sources = (await collectSources(SOURCE_DIR)).sort();
	if (sources.length === 0) {
		console.warn("optimise-images: no source images found in public/images");
		return;
	}

	await mkdir(OUTPUT_DIR, { recursive: true });

	const images = {};
	const expected = new Set();
	let sourceBytes = 0;
	let derivativeBytes = 0;
	let written = 0;

	for (const source of sources) {
		const contents = await readFile(source);
		const info = await stat(source);
		sourceBytes += info.size;

		const hash = createHash("sha256").update(contents).digest("hex").slice(0, 8);
		const { width, height } = await sharp(contents).metadata();
		const name = path.basename(source, path.extname(source));

		// Never upscale: the ladder stops at the source width, and an image
		// narrower than the smallest step still gets a single derivative.
		const targets = WIDTHS.filter((w) => w <= Math.min(width, MAX_WIDTH));
		if (targets.length === 0) targets.push(Math.min(width, MAX_WIDTH));

		const variants = [];
		for (const target of targets) {
			const { variant, skipped } = await buildVariant(
				contents,
				hash,
				name,
				target,
				info.mtimeMs,
				width,
				height,
			);
			expected.add(variant.file);
			variants.push(variant);
			if (!skipped) written += 1;
			try {
				derivativeBytes += (await stat(path.join(OUTPUT_DIR, variant.file))).size;
			} catch {
				// Not fatal: the size report is informational only.
			}
		}

		images[publicPath(source)] = { width, height, hash, variants };
	}

	// Drop derivatives whose source image was renamed or removed, so the deploy
	// does not accumulate orphans that nothing references.
	for (const entry of await readdir(OUTPUT_DIR)) {
		if (!expected.has(entry)) await unlink(path.join(OUTPUT_DIR, entry));
	}

	await writeManifest(images);

	console.log(
		`optimise-images: ${sources.length} source images (${kb(sourceBytes)}) -> ` +
			`${expected.size} WebP derivatives (${kb(derivativeBytes)}); ${written} written this run.`,
	);
}

main().catch((error) => {
	console.error("optimise-images failed:", error);
	process.exitCode = 1;
});
