// AUTO-GENERATED by scripts/optimise-images.mjs — do not edit by hand.
// Regenerate with `npm run images` (also run automatically by prebuild/predev).
//
// Maps each source image's public URL to its intrinsic size and the resized
// WebP derivatives available for it. Consumed by src/lib/images.ts.

export interface ImageVariant {
	/** Width in pixels. */
	w: number;
	/** Height in pixels — used for the width/height attributes that reserve space. */
	h: number;
	/** File name within /images/opt/. */
	file: string;
}

export interface ImageRecord {
	/** Intrinsic width of the original image. */
	width: number;
	/** Intrinsic height of the original image. */
	height: number;
	/** Source-content hash embedded in every derivative file name. */
	hash: string;
	/** Derivatives, narrowest first. */
	variants: ImageVariant[];
}

export const PIPELINE_VERSION = 1;

export const IMAGE_MANIFEST: Record<string, ImageRecord> = {
	"/images/MR-image_sheet.jpg": {
		"width": 4160,
		"height": 6240,
		"hash": "0b44bf72",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "MR-image_sheet.0b44bf72-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "MR-image_sheet.0b44bf72-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "MR-image_sheet.0b44bf72-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "MR-image_sheet.0b44bf72-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "MR-image_sheet.0b44bf72-1920.webp"
			}
		]
	},
	"/images/XR-spine_radiograph.jpg": {
		"width": 4160,
		"height": 6240,
		"hash": "5c957330",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "XR-spine_radiograph.5c957330-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "XR-spine_radiograph.5c957330-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "XR-spine_radiograph.5c957330-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "XR-spine_radiograph.5c957330-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "XR-spine_radiograph.5c957330-1920.webp"
			}
		]
	},
	"/images/consult-room.jpg": {
		"width": 600,
		"height": 900,
		"hash": "1d05fae8",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "consult-room.1d05fae8-480.webp"
			}
		]
	},
	"/images/ct_scanner.jpg": {
		"width": 3648,
		"height": 5472,
		"hash": "1d068d81",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "ct_scanner.1d068d81-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "ct_scanner.1d068d81-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "ct_scanner.1d068d81-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "ct_scanner.1d068d81-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "ct_scanner.1d068d81-1920.webp"
			}
		]
	},
	"/images/head_ct_images.jpg": {
		"width": 6240,
		"height": 4160,
		"hash": "3470a3da",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "head_ct_images.3470a3da-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "head_ct_images.3470a3da-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "head_ct_images.3470a3da-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "head_ct_images.3470a3da-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "head_ct_images.3470a3da-1920.webp"
			}
		]
	},
	"/images/hero-medical.jpg": {
		"width": 1920,
		"height": 1280,
		"hash": "fd982db4",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "hero-medical.fd982db4-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "hero-medical.fd982db4-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "hero-medical.fd982db4-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "hero-medical.fd982db4-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "hero-medical.fd982db4-1920.webp"
			}
		]
	},
	"/images/knee_xray_pen_pointing.jpg": {
		"width": 5760,
		"height": 3840,
		"hash": "030ec1ff",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "knee_xray_pen_pointing.030ec1ff-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "knee_xray_pen_pointing.030ec1ff-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "knee_xray_pen_pointing.030ec1ff-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "knee_xray_pen_pointing.030ec1ff-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "knee_xray_pen_pointing.030ec1ff-1920.webp"
			}
		]
	},
	"/images/og-default.jpg": {
		"width": 1200,
		"height": 630,
		"hash": "948601a4",
		"variants": [
			{
				"w": 480,
				"h": 252,
				"file": "og-default.948601a4-480.webp"
			},
			{
				"w": 768,
				"h": 403,
				"file": "og-default.948601a4-768.webp"
			},
			{
				"w": 1024,
				"h": 538,
				"file": "og-default.948601a4-1024.webp"
			}
		]
	},
	"/images/open_mr_scanner.jpg": {
		"width": 2800,
		"height": 1868,
		"hash": "108a649e",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "open_mr_scanner.108a649e-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "open_mr_scanner.108a649e-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "open_mr_scanner.108a649e-1024.webp"
			},
			{
				"w": 1440,
				"h": 961,
				"file": "open_mr_scanner.108a649e-1440.webp"
			},
			{
				"w": 1920,
				"h": 1281,
				"file": "open_mr_scanner.108a649e-1920.webp"
			}
		]
	},
	"/images/oxford_bookshop.jpg": {
		"width": 8686,
		"height": 5791,
		"hash": "1386475c",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "oxford_bookshop.1386475c-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "oxford_bookshop.1386475c-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "oxford_bookshop.1386475c-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "oxford_bookshop.1386475c-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "oxford_bookshop.1386475c-1920.webp"
			}
		]
	},
	"/images/oxford_medieval_corridor.jpg": {
		"width": 8684,
		"height": 5790,
		"hash": "62119025",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "oxford_medieval_corridor.62119025-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "oxford_medieval_corridor.62119025-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "oxford_medieval_corridor.62119025-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "oxford_medieval_corridor.62119025-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "oxford_medieval_corridor.62119025-1920.webp"
			}
		]
	},
	"/images/pexels-charlss-gonzhu-433318654-15277956.jpg": {
		"width": 5278,
		"height": 3519,
		"hash": "1c77796c",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-charlss-gonzhu-433318654-15277956.1c77796c-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "pexels-charlss-gonzhu-433318654-15277956.1c77796c-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "pexels-charlss-gonzhu-433318654-15277956.1c77796c-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "pexels-charlss-gonzhu-433318654-15277956.1c77796c-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "pexels-charlss-gonzhu-433318654-15277956.1c77796c-1920.webp"
			}
		]
	},
	"/images/pexels-cottonbro-5723875.jpg": {
		"width": 4130,
		"height": 6195,
		"hash": "b423a8e7",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-cottonbro-5723875.b423a8e7-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-cottonbro-5723875.b423a8e7-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-cottonbro-5723875.b423a8e7-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-cottonbro-5723875.b423a8e7-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-cottonbro-5723875.b423a8e7-1920.webp"
			}
		]
	},
	"/images/pexels-cottonbro-5723878.jpg": {
		"width": 4160,
		"height": 6240,
		"hash": "655ac8a6",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-cottonbro-5723878.655ac8a6-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-cottonbro-5723878.655ac8a6-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-cottonbro-5723878.655ac8a6-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-cottonbro-5723878.655ac8a6-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-cottonbro-5723878.655ac8a6-1920.webp"
			}
		]
	},
	"/images/pexels-cottonbro-5723881.jpg": {
		"width": 3979,
		"height": 5968,
		"hash": "bb0d37f1",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-cottonbro-5723881.bb0d37f1-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-cottonbro-5723881.bb0d37f1-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-cottonbro-5723881.bb0d37f1-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-cottonbro-5723881.bb0d37f1-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-cottonbro-5723881.bb0d37f1-1920.webp"
			}
		]
	},
	"/images/pexels-cottonbro-6202736.jpg": {
		"width": 4160,
		"height": 6240,
		"hash": "bed3da36",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-cottonbro-6202736.bed3da36-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-cottonbro-6202736.bed3da36-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-cottonbro-6202736.bed3da36-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-cottonbro-6202736.bed3da36-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-cottonbro-6202736.bed3da36-1920.webp"
			}
		]
	},
	"/images/pexels-cottonbro-6502022.jpg": {
		"width": 6720,
		"height": 4480,
		"hash": "3ce172a9",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-cottonbro-6502022.3ce172a9-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "pexels-cottonbro-6502022.3ce172a9-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "pexels-cottonbro-6502022.3ce172a9-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "pexels-cottonbro-6502022.3ce172a9-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "pexels-cottonbro-6502022.3ce172a9-1920.webp"
			}
		]
	},
	"/images/pexels-cottonbro-7579832.jpg": {
		"width": 4315,
		"height": 6473,
		"hash": "ba1876ed",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-cottonbro-7579832.ba1876ed-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-cottonbro-7579832.ba1876ed-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-cottonbro-7579832.ba1876ed-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-cottonbro-7579832.ba1876ed-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-cottonbro-7579832.ba1876ed-1920.webp"
			}
		]
	},
	"/images/pexels-gustavo-fring-7446994.jpg": {
		"width": 3840,
		"height": 5760,
		"hash": "fc3ba5c5",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-gustavo-fring-7446994.fc3ba5c5-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-gustavo-fring-7446994.fc3ba5c5-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-gustavo-fring-7446994.fc3ba5c5-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-gustavo-fring-7446994.fc3ba5c5-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-gustavo-fring-7446994.fc3ba5c5-1920.webp"
			}
		]
	},
	"/images/pexels-gustavo-fring-7446998.jpg": {
		"width": 5760,
		"height": 3840,
		"hash": "d9afbbe7",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-gustavo-fring-7446998.d9afbbe7-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "pexels-gustavo-fring-7446998.d9afbbe7-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "pexels-gustavo-fring-7446998.d9afbbe7-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "pexels-gustavo-fring-7446998.d9afbbe7-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "pexels-gustavo-fring-7446998.d9afbbe7-1920.webp"
			}
		]
	},
	"/images/pexels-konrads-photo-32251894.jpg": {
		"width": 4000,
		"height": 6000,
		"hash": "617d9788",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-konrads-photo-32251894.617d9788-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-konrads-photo-32251894.617d9788-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-konrads-photo-32251894.617d9788-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-konrads-photo-32251894.617d9788-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-konrads-photo-32251894.617d9788-1920.webp"
			}
		]
	},
	"/images/pexels-konrads-photo-37406596.jpg": {
		"width": 4000,
		"height": 6000,
		"hash": "e02420f2",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-konrads-photo-37406596.e02420f2-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-konrads-photo-37406596.e02420f2-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-konrads-photo-37406596.e02420f2-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-konrads-photo-37406596.e02420f2-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-konrads-photo-37406596.e02420f2-1920.webp"
			}
		]
	},
	"/images/pexels-mart-production-7089331.jpg": {
		"width": 3936,
		"height": 2624,
		"hash": "803de2bd",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-mart-production-7089331.803de2bd-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "pexels-mart-production-7089331.803de2bd-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "pexels-mart-production-7089331.803de2bd-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "pexels-mart-production-7089331.803de2bd-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "pexels-mart-production-7089331.803de2bd-1920.webp"
			}
		]
	},
	"/images/pexels-mart-production-7089390.jpg": {
		"width": 4000,
		"height": 6000,
		"hash": "873e8ad1",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-mart-production-7089390.873e8ad1-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-mart-production-7089390.873e8ad1-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-mart-production-7089390.873e8ad1-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-mart-production-7089390.873e8ad1-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-mart-production-7089390.873e8ad1-1920.webp"
			}
		]
	},
	"/images/pexels-mart-production-7089402.jpg": {
		"width": 3560,
		"height": 5340,
		"hash": "2ff9d716",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-mart-production-7089402.2ff9d716-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-mart-production-7089402.2ff9d716-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-mart-production-7089402.2ff9d716-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-mart-production-7089402.2ff9d716-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-mart-production-7089402.2ff9d716-1920.webp"
			}
		]
	},
	"/images/pexels-maxmishin-11119416.jpg": {
		"width": 6123,
		"height": 4082,
		"hash": "5c9bb2b9",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-maxmishin-11119416.5c9bb2b9-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "pexels-maxmishin-11119416.5c9bb2b9-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "pexels-maxmishin-11119416.5c9bb2b9-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "pexels-maxmishin-11119416.5c9bb2b9-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "pexels-maxmishin-11119416.5c9bb2b9-1920.webp"
			}
		]
	},
	"/images/pexels-pavel-danilyuk-6812468.jpg": {
		"width": 5473,
		"height": 3654,
		"hash": "7ee2f2db",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-pavel-danilyuk-6812468.7ee2f2db-480.webp"
			},
			{
				"w": 768,
				"h": 513,
				"file": "pexels-pavel-danilyuk-6812468.7ee2f2db-768.webp"
			},
			{
				"w": 1024,
				"h": 684,
				"file": "pexels-pavel-danilyuk-6812468.7ee2f2db-1024.webp"
			},
			{
				"w": 1440,
				"h": 961,
				"file": "pexels-pavel-danilyuk-6812468.7ee2f2db-1440.webp"
			},
			{
				"w": 1920,
				"h": 1282,
				"file": "pexels-pavel-danilyuk-6812468.7ee2f2db-1920.webp"
			}
		]
	},
	"/images/pexels-rdne-6129206.jpg": {
		"width": 4425,
		"height": 6637,
		"hash": "a133ab54",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-rdne-6129206.a133ab54-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-rdne-6129206.a133ab54-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-rdne-6129206.a133ab54-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-rdne-6129206.a133ab54-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-rdne-6129206.a133ab54-1920.webp"
			}
		]
	},
	"/images/pexels-shvetsa-4225925.jpg": {
		"width": 6158,
		"height": 4105,
		"hash": "f60da1cd",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "pexels-shvetsa-4225925.f60da1cd-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "pexels-shvetsa-4225925.f60da1cd-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "pexels-shvetsa-4225925.f60da1cd-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "pexels-shvetsa-4225925.f60da1cd-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "pexels-shvetsa-4225925.f60da1cd-1920.webp"
			}
		]
	},
	"/images/pexels-shvetsa-4226205.jpg": {
		"width": 4160,
		"height": 6240,
		"hash": "5c957330",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-shvetsa-4226205.5c957330-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-shvetsa-4226205.5c957330-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-shvetsa-4226205.5c957330-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-shvetsa-4226205.5c957330-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-shvetsa-4226205.5c957330-1920.webp"
			}
		]
	},
	"/images/pexels-tima-miroshnichenko-5452281.jpg": {
		"width": 4000,
		"height": 6000,
		"hash": "9b6e9ad5",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "pexels-tima-miroshnichenko-5452281.9b6e9ad5-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "pexels-tima-miroshnichenko-5452281.9b6e9ad5-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "pexels-tima-miroshnichenko-5452281.9b6e9ad5-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "pexels-tima-miroshnichenko-5452281.9b6e9ad5-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "pexels-tima-miroshnichenko-5452281.9b6e9ad5-1920.webp"
			}
		]
	},
	"/images/pexels-valery-arispe-2149327983-34170810.jpg": {
		"width": 4000,
		"height": 5328,
		"hash": "d5e479bb",
		"variants": [
			{
				"w": 480,
				"h": 639,
				"file": "pexels-valery-arispe-2149327983-34170810.d5e479bb-480.webp"
			},
			{
				"w": 768,
				"h": 1023,
				"file": "pexels-valery-arispe-2149327983-34170810.d5e479bb-768.webp"
			},
			{
				"w": 1024,
				"h": 1364,
				"file": "pexels-valery-arispe-2149327983-34170810.d5e479bb-1024.webp"
			},
			{
				"w": 1440,
				"h": 1918,
				"file": "pexels-valery-arispe-2149327983-34170810.d5e479bb-1440.webp"
			},
			{
				"w": 1920,
				"h": 2557,
				"file": "pexels-valery-arispe-2149327983-34170810.d5e479bb-1920.webp"
			}
		]
	},
	"/images/portrait-dr.jpg": {
		"width": 900,
		"height": 600,
		"hash": "4492052b",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "portrait-dr.4492052b-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "portrait-dr.4492052b-768.webp"
			}
		]
	},
	"/images/reporting-room.jpg": {
		"width": 1280,
		"height": 854,
		"hash": "30f65b29",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "reporting-room.30f65b29-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "reporting-room.30f65b29-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "reporting-room.30f65b29-1024.webp"
			}
		]
	},
	"/images/reporting_radiographer.jpg": {
		"width": 3936,
		"height": 5904,
		"hash": "9d00d78b",
		"variants": [
			{
				"w": 480,
				"h": 720,
				"file": "reporting_radiographer.9d00d78b-480.webp"
			},
			{
				"w": 768,
				"h": 1152,
				"file": "reporting_radiographer.9d00d78b-768.webp"
			},
			{
				"w": 1024,
				"h": 1536,
				"file": "reporting_radiographer.9d00d78b-1024.webp"
			},
			{
				"w": 1440,
				"h": 2160,
				"file": "reporting_radiographer.9d00d78b-1440.webp"
			},
			{
				"w": 1920,
				"h": 2880,
				"file": "reporting_radiographer.9d00d78b-1920.webp"
			}
		]
	},
	"/images/spine_CT.jpg": {
		"width": 6187,
		"height": 4125,
		"hash": "f450eb74",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "spine_CT.f450eb74-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "spine_CT.f450eb74-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "spine_CT.f450eb74-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "spine_CT.f450eb74-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "spine_CT.f450eb74-1920.webp"
			}
		]
	},
	"/images/xr_spine_radiograph_2.jpg": {
		"width": 6240,
		"height": 4160,
		"hash": "93c98758",
		"variants": [
			{
				"w": 480,
				"h": 320,
				"file": "xr_spine_radiograph_2.93c98758-480.webp"
			},
			{
				"w": 768,
				"h": 512,
				"file": "xr_spine_radiograph_2.93c98758-768.webp"
			},
			{
				"w": 1024,
				"h": 683,
				"file": "xr_spine_radiograph_2.93c98758-1024.webp"
			},
			{
				"w": 1440,
				"h": 960,
				"file": "xr_spine_radiograph_2.93c98758-1440.webp"
			},
			{
				"w": 1920,
				"h": 1280,
				"file": "xr_spine_radiograph_2.93c98758-1920.webp"
			}
		]
	}
};
